/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":minestom-mechanics-lib"))
    api(libs.net.minestom.minestom)
    api(libs.ch.qos.logback.logback.classic)
    api(libs.it.unimi.dsi.fastutil)
}

description = "Minestom Test Server"
