/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.net.minestom.minestom)
    api(libs.it.unimi.dsi.fastutil)
    api(libs.com.google.code.gson.gson)
}

description = "Minestom Mechanics Library"

java {
    withJavadocJar()
}
